# Generated by Django 4.1.5 on 2023-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_comment', models.IntegerField(blank=True, max_length=10)),
                ('comment', models.CharField(max_length=77)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('p_key', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('title_topic', models.CharField(max_length=100)),
                ('text_topic', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('p_key_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=77)),
                ('password_user', models.CharField(max_length=100)),
            ],
        ),
    ]
