# Generated by Django 4.1.1 on 2022-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('p_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title_topic', models.CharField(max_length=100)),
                ('text_topic', models.CharField(max_length=300)),
            ],
        ),
    ]
