# Generated by Django 4.1.1 on 2022-09-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='p_key',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
