# Generated by Django 4.1.5 on 2023-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='p_key',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
