# Generated by Django 4.1.1 on 2022-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topics_p_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('p_key_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=77)),
                ('password_user', models.CharField(max_length=100)),
            ],
        ),
    ]
