# Generated by Django 4.1.5 on 2023-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topics_p_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='key_comment',
            field=models.IntegerField(blank=True),
        ),
    ]
